using System; using System.Collections.Generic; using System.Linq; using dk.gi.app.ejendom.tjekejerskifte.Application.Abstractions; using dk.gi.app.ejendom.tjekejerskifte.Application.Models; using Microsoft.PowerPlatform.Dataverse.Client; using Microsoft.Xrm.Sdk; using Microsoft.Xrm.Sdk.Query;
namespace dk.gi.app.ejendom.tjekejerskifte.Infrastructure.Crm.Dataverse
{
 public sealed class EjendomTjekEjerskifteDataverseClient : IEjendomTjekEjerskifteScanClient
 {
  private const string PropertyLogicalName = "ap_ejendom"; private const string ConfigLogicalName = "config_configurationsetting"; private const string PropertyId = "ap_ejendid"; private const string PropertyBfe = "ap_bfenummer"; private const string PropertyBfeMother = "ap_bfenummermoderejendom"; private const string PropertyLastChecked = "ap_tinglysningsidstkontrolleretdato"; private const string PropertyLastDeedDate = "ap_sidsteskoededato"; private const string PropertyMunicipality = "ap_kommunenummer"; private const string PropertyNumber = "ap_ejendomsnummer"; private const string PropertyBbr = "ap_bbrnummer"; private const string PropertyStateCode = "statecode"; private const string PropertyExcludeAutoCheck = "ap_undtagesforautomatiskskoededatotjek"; private const string ConfigName = "config_name"; private const string ConfigValue = "config_ntextcolumn"; private const string ServiceBusConfigPrefix = "Azure.Service.Bus.Queue.Crm.Indbakke."; private readonly ServiceClient _serviceClient; private readonly IOrganizationService _service; private readonly Action<string> _trace; private bool _disposed;
  public EjendomTjekEjerskifteDataverseClient(string connectionString, int timeOutMinutes, Action<string> trace = null) { _trace = trace; ServiceClient.MaxConnectionTimeout = TimeSpan.FromMinutes(Math.Max(1, timeOutMinutes)); _serviceClient = new ServiceClient(connectionString); _service = _serviceClient; if (!_serviceClient.IsReady) throw new InvalidOperationException("Dataverse klient kunne ikke oprettes: " + _serviceClient.LastError); }
  public EjendomTjekEjerskifteExecutionSummary VerifyConnection() { var query = new QueryExpression(PropertyLogicalName) { ColumnSet = new ColumnSet(PropertyMunicipality), TopCount = 1, NoLock = true }; _service.RetrieveMultiple(query); return new EjendomTjekEjerskifteExecutionSummary(true, 0, 0, 0, "Dataverse-forbindelse verificeret.", "local dataverse sdk"); }
  public IReadOnlyCollection<EjendomTjekEjerskifteCandidate> GetCandidates(EjendomTjekEjerskifteRequest request) { var query = new QueryExpression(PropertyLogicalName) { ColumnSet = new ColumnSet(PropertyBfe, PropertyBfeMother, PropertyMunicipality, PropertyNumber, PropertyBbr, PropertyLastDeedDate, PropertyLastChecked), Distinct = false, NoLock = true, PageInfo = new PagingInfo { PageNumber = 1, Count = Math.Max(1, Math.Min(request.MaxAntal, 4999)) } }; query.Criteria.AddCondition(PropertyStateCode, ConditionOperator.Equal, 0); query.Criteria.AddCondition(PropertyExcludeAutoCheck, ConditionOperator.NotEqual, true); var filter = new FilterExpression(LogicalOperator.Or); filter.AddCondition(PropertyLastChecked, ConditionOperator.Null); filter.AddCondition(PropertyLastChecked, ConditionOperator.OlderThanXDays, Math.Max(0, request.MaxDage)); query.Criteria.AddFilter(filter); query.AddOrder(PropertyMunicipality, OrderType.Ascending); return RetrieveAll(query, "ejendom-tjekejerskifte-candidates").Take(Math.Max(1, Math.Min(request.MaxAntal, 4999))).Select(entity => new EjendomTjekEjerskifteCandidate(entity.Id, entity.GetAttributeValue<string>(PropertyMunicipality) ?? string.Empty, entity.GetAttributeValue<string>(PropertyNumber) ?? string.Empty, entity.GetAttributeValue<string>(PropertyBbr) ?? string.Empty, entity.GetAttributeValue<string>(PropertyBfe) ?? string.Empty, entity.GetAttributeValue<string>(PropertyBfeMother) ?? string.Empty, entity.Attributes.Contains(PropertyLastDeedDate) ? (DateTime?)entity.GetAttributeValue<DateTime>(PropertyLastDeedDate) : null)).ToList(); }
  public ResolvedServiceBusSettings ResolveServiceBusSettings() { var values = RetrieveConfigurationValues(ServiceBusConfigPrefix); string serviceBusName; string sasKeyName; string sasKey; values.TryGetValue(ServiceBusConfigPrefix + "ServiceBusName", out serviceBusName); values.TryGetValue(ServiceBusConfigPrefix + "SharedAccessKeyName", out sasKeyName); values.TryGetValue(ServiceBusConfigPrefix + "SharedAccessKey", out sasKey); if (string.IsNullOrWhiteSpace(serviceBusName) || string.IsNullOrWhiteSpace(sasKeyName) || string.IsNullOrWhiteSpace(sasKey)) return ResolvedServiceBusSettings.Empty("crm config_configurationsetting"); return new ResolvedServiceBusSettings("https://" + serviceBusName.Trim().TrimEnd('/') + ".servicebus.windows.net", sasKeyName.Trim(), sasKey.Trim(), "crm config_configurationsetting"); }
  private Dictionary<string, string> RetrieveConfigurationValues(string prefix) { var query = new QueryExpression(ConfigLogicalName) { ColumnSet = new ColumnSet(ConfigName, ConfigValue), Distinct = false, NoLock = true, PageInfo = new PagingInfo { PageNumber = 1, Count = 500 } }; query.Criteria.AddCondition(ConfigName, ConditionOperator.BeginsWith, prefix); var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase); foreach (var entity in RetrieveAll(query, "ejendom-tjekejerskifte-config")) { string name = entity.GetAttributeValue<string>(ConfigName); string value = entity.GetAttributeValue<string>(ConfigValue); if (!string.IsNullOrWhiteSpace(name)) result[name.Trim()] = value ?? string.Empty; } return result; }
  private List<Entity> RetrieveAll(QueryExpression query, string operationName) { var result = new List<Entity>(); string pagingCookie = null; int pageNumber = 1; while (true) { query.PageInfo = query.PageInfo ?? new PagingInfo(); query.PageInfo.PageNumber = pageNumber; query.PageInfo.PagingCookie = pagingCookie; EntityCollection response = _service.RetrieveMultiple(query); if (response?.Entities != null && response.Entities.Count > 0) result.AddRange(response.Entities); _trace?.Invoke(operationName + ": side=" + pageNumber + ", hentet=" + (response?.Entities?.Count ?? 0) + "."); if (response == null || !response.MoreRecords) break; pageNumber++; pagingCookie = response.PagingCookie; } return result; }
  public void Dispose() { if (_disposed) return; _disposed = true; _serviceClient.Dispose(); }
 }
}
